services:
  postgres:
    image: postgres:16
    container_name: climate_postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: climate_user
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: climate_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: climate_app

    depends_on:
      - postgres

    environment:
      DB_HOST: postgres
      DB_USER: climate_user
      DB_PASSWORD: 123
      DB_NAME: climate_db

    command: uv run main.py

volumes:
  postgres_data: